version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
        APP_ENV: ${APP_ENV}
        HTTP_URL: ${HTTP_URL}
        HTTP_PORT: ${HTTP_PORT}
        HTTP_ALLOWED_ORIGINS: ${HTTP_ALLOWED_ORIGINS}
        PRIVATE_KEY: ${PRIVATE_KEY}
        PUBLIC_KEY: ${PUBLIC_KEY}
        TOKEN_DURATION: ${TOKEN_DURATION}

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: