version: "3.9"

services:
  coupon:
    image: almendraivan/microservice-coupon:v25
    ports:
      - "4000:4000"
    networks:
      - shared_network

  uala:
    image: almendraivan/microservice-uala:v10
    container_name: uala
    ports:
      - "5000:5000"
    volumes:
      - ./photos-data:/app/image
    networks:
      - shared_network

  frontend:
    image: almendraivan/microservice-frontend:v1
    ports:
      - "3000:3000"
    networks:
      - shared_network

networks:
  shared_network:
