version: "3.9"

services:
  nodejs-ualabis:
    container_name: nodejs-ualabis
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - USER_NAME_UALA=$USER_NAME_UALA
      - CLIENT_ID_UALA=$CLIENT_ID_UALA
      - CLIENT_SECRET_ID=$CLIENT_SECRET_ID
      - PORT=$PORT
    ports:
      - "5000:5000"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
